In [ ]:
# 9th July, 2026 (v27.ipynb)
# Learned Pandas

In [ ]:
import pandas as pd
name_list = ['Ford', 'Ferrari', 'Lamborghini', 'Toyota']
names = pd.Series(name_list)
names

0           Ford
1        Ferrari
2    Lamborghini
3         Toyota
dtype: object

In [ ]:
# left

In [ ]:
data = pd.Series([5, 10, 15, 20], index = ['a', 'b', 'c', 'd'])
data

a     5
b    10
c    15
d    20
dtype: int64

In [ ]:
# Access data from Series
# numerical indexing/slicing as numpy
print(data[0])
print(data[0:4])

5
a     5
b    10
c    15
d    20
dtype: int64

/tmp/ipykernel_2889/1257040865.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(data[0])

In [ ]:
# accessing the data using real index
print(data['d'])

20

In [ ]:
# Dataframe: whole table
import pandas as pd
name_list = ['Ford', 'Ferrari', 'Lamborghini', 'Toyota']
names =pd.Series(name_list)
# Creating dataframe
df = pd.DataFrame()
df['Company'] = names
df

       Company
0         Ford
1      Ferrari
2  Lamborghini
3       Toyota

In [ ]:
import pandas as pd
# Create list
name_list = ['Ford', 'Ferrari', 'Lamborghini', 'Toyota']
shift_list = [1, 1, 1, 0]
color_list = ['red', 'blue', 'white', 'white']
door_list = [4, 2, 2, 4]

# convert to series
names =pd.Series(name_list)
shift =pd.Series(shift_list)
color =pd.Series(color_list)
door =pd.Series(door_list)

# Creating dataframe
df = pd.DataFrame()
df['Company'] = names
df['Automatic Shift'] = shift
df['Color'] = color
df['Number of doors'] = door
df

       Company  Automatic Shift  Color  Number of doors
0         Ford                1    red                4
1      Ferrari                1   blue                2
2  Lamborghini                1  white                2
3       Toyota                0  white                4

In [ ]:
# Above step by step is difficult and long
# Pandas makes it easy

In [ ]:
# Easy way
import pandas as pd

# Create list
name_list = ['Ford', 'Ferrari', 'Lamborghini', 'Toyota']
shift_list = [1, 1, 1, 0]
color_list = ['red', 'blue', 'white', 'white']
door_list = [4, 2, 2, 4]

# create dataframe using dictionary method
df = pd.DataFrame(data = {'Company': name_list,
                          'Automatic_shift': shift_list,
                          'Color': color_list,
                          'Number of doors': door_list})
df

       Company  Automatic_shift  Color  Number of doors
0         Ford                1    red                4
1      Ferrari                1   blue                2
2  Lamborghini                1  white                2
3       Toyota                0  white                4

In [ ]:
df.shape

(4, 4)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Company          4 non-null      object
 1   Automatic_shift  4 non-null      int64
 2   Color            4 non-null      object
 3   Number of doors  4 non-null      int64
dtypes: int64(2), object(2)
memory usage: 260.0+ bytes

In [ ]:
df.describe()

       Automatic_shift  Number of doors
count             4.00         4.000000
mean              0.75         3.000000
std               0.50         1.154701
min               0.00         2.000000
25%               0.75         2.000000
50%               1.00         3.000000
75%               1.00         4.000000
max               1.00         4.000000

In [ ]:
# Create Dataframe

import pandas as pd

A = ['a', 'b', 'c', 'd', 'e']

# left

In [ ]:
# Reading CSV file into DataFrame

In [ ]:
import pandas as pd
dataset_path = ('/content/Salary_Data.csv')

df = pd.read_csv(dataset_path)
df

,Age,Gender,Education Level,Job Title,Years of Experience,Salary
0,32.0,Male,Bachelor's,Software Engineer,5.0,90000.0
1,28.0,Female,Master's,Data Analyst,3.0,65000.0
2,45.0,Male,PhD,Senior Manager,15.0,150000.0
3,36.0,Female,Bachelor's,Sales Associate,7.0,60000.0
4,52.0,Male,Master's,Director,20.0,200000.0
...,...,...,...,...,...,...
370,35.0,Female,Bachelor's,Senior Marketing Analyst,8.0,85000.0
371,43.0,Male,Master's,Director of Operations,19.0,170000.0
372,29.0,Female,Bachelor's,Junior Project Manager,2.0,40000.0
373,34.0,Male,Bachelor's,Senior Operations Coordinator,7.0,90000.0
374,44.0,Female,PhD,Senior Business Analyst,15.0,150000.0

In [ ]:
df.head() # gives first 5 data

,Age,Gender,Education Level,Job Title,Years of Experience,Salary
0,32.0,Male,Bachelor's,Software Engineer,5.0,90000.0
1,28.0,Female,Master's,Data Analyst,3.0,65000.0
2,45.0,Male,PhD,Senior Manager,15.0,150000.0
3,36.0,Female,Bachelor's,Sales Associate,7.0,60000.0
4,52.0,Male,Master's,Director,20.0,200000.0

In [ ]:
df.tail() # gives last 5 data

,Age,Gender,Education Level,Job Title,Years of Experience,Salary
370,35.0,Female,Bachelor's,Senior Marketing Analyst,8.0,85000.0
371,43.0,Male,Master's,Director of Operations,19.0,170000.0
372,29.0,Female,Bachelor's,Junior Project Manager,2.0,40000.0
373,34.0,Male,Bachelor's,Senior Operations Coordinator,7.0,90000.0
374,44.0,Female,PhD,Senior Business Analyst,15.0,150000.0

In [ ]:
# Pandas Libray: 2nd Chapter 1
# In chapter 1 we learned series, dataframe and basics of Pandas
# Now we will learn about selecting rows, columns, deal with missing values

In [ ]:
# Selecting rows and columns
# using iloc and loc

In [ ]:
import pandas as pd
data = {     "Name": ["Alice", "Bob", "Charlie", "David"],
              "Age": [23, 25, 22, 24],
             "City": ["NY", "LA", "Chicago", "Boston"] }
df = pd.DataFrame(data)
df

      Name  Age     City
0    Alice   23       NY
1      Bob   25       LA
2  Charlie   22  Chicago
3    David   24   Boston

In [ ]:
# loc - label based indexing
# loc - full form is 'location'
# In the pandas library, loc stands for "location". It is a property used for label-based indexing to
# access specific rows and columns in a DataFrame or Series.
# select a row by a label
print(df.loc[0])
# print(df.loc[3])

Name    Alice
Age        23
City       NY
Name: 0, dtype: object
Name     David
Age         24
City    Boston
Name: 3, dtype: object

In [ ]:
# Selecting multiple rows
print(df.loc[[0, 1]])
# print(df.loc[[0, 1, 2]])

    Name  Age City
0  Alice   23   NY
1    Bob   25   LA
      Name  Age     City
0    Alice   23       NY
1      Bob   25       LA
2  Charlie   22  Chicago

In [ ]:
# select row and coloum
print(df.loc[2, "Name"])

Charlie

In [ ]:
# Multiple columns
print(df.loc[:, ["Name", "Age"]])

      Name  Age
0    Alice   23
1      Bob   25
2  Charlie   22
3    David   24

In [ ]:
# slice rows
print(df.loc[1:3]) # gives row 0, 1, 2

      Name  Age     City
1      Bob   25       LA
2  Charlie   22  Chicago
3    David   24   Boston

In [ ]:
# using filter on Age
print(df.loc[df['Age'] > 23])

    Name  Age    City
1    Bob   25      LA
3  David   24  Boston

In [ ]:
# iloc - position base indexing
# iloc -> full form is 'Integer Location'
# In pandas, iloc is a property used for purely integer-based indexing. It allows you to select rows and
# columns from a DataFrame or Series by their numerical position (0-indexed), regardless of their text label

In [ ]:
# selecting first row
print(df.iloc[0])

Name    Alice
Age        23
City       NY
Name: 0, dtype: object

In [ ]:
# row and column
print(df.iloc[2, 0])

Charlie

In [ ]:
print(df.iloc[:, 0:2])

      Name  Age
0    Alice   23
1      Bob   25
2  Charlie   22
3    David   24

In [ ]:
# difference between loc and iloc
print("***** iloc *****\n")
print(df.loc[1:3])
print("\n")
print("***** iloc *****\n")
print(df.iloc[1:3])

***** iloc *****

      Name  Age     City
1      Bob   25       LA
2  Charlie   22  Chicago
3    David   24   Boston


***** iloc *****

      Name  Age     City
1      Bob   25       LA
2  Charlie   22  Chicago

In [ ]:
#   Name	    Age	  City
# 0	Alice	    23	  NY
# 1	Bob	      25	  LA
# 2	Charlie	  22	  Chicago
# 3	David	    24	  Boston

# [0, 3] -> 1st row and 4th row from above dataset
# [0, 2] -> 1st column and 3rd column from above dataset
print(df.iloc[[0, 3], [0, 2]])

    Name    City
0  Alice      NY
3  David  Boston