In [ ]:
# 12 july, 2026 (v28)
# Learned remaining pandas (data manipulation), joins, concatenation

In [ ]:
import pandas as pd
import numpy as np
A = ['a','b','c','d']
B = ['e',np.nan,'g','h']
C = ['i', 'j', np.nan, 'l']
D = ['a', 'e', 'i', 'o']
E = ['s', 'k', np.nan, 'g']
#create dataframe
df = pd.DataFrame(data=[A, B, C, D, E], columns=['one', 'two', 'three', 'four'])

#display dataframe
df

  one  two three four
0   a    b     c    d
1   e  NaN     g    h
2   i    j   NaN    l
3   a    e     i    o
4   s    k   NaN    g

In [ ]:
# Fillna()

In [ ]:
# inplace
df.fillna(2, inplace=True)

In [ ]:
df

  one two three four
0   a   b     c    d
1   e   2     g    h
2   i   j     2    l
3   a   e     i    o
4   s   k     2    g

In [ ]:
# drop_na()

In [ ]:
import pandas as pd
import numpy as np
A = ['a','b','c','d']
B = ['e',np.nan,'g','h']
C = ['i', 'j', np.nan, 'l']
D = ['a', 'e', 'i', 'o']
E = ['s', 'k', np.nan, 'g']
#create dataframe
df = pd.DataFrame(data=[A, B, C, D, E], columns=['one', 'two', 'three', 'four'])

#display dataframe
df

  one  two three four
0   a    b     c    d
1   e  NaN     g    h
2   i    j   NaN    l
3   a    e     i    o
4   s    k   NaN    g

In [ ]:
# when to drop rows and when to drop columns
# ....

In [ ]:
df.dropna(axis = 0) # drops the row where there is null value or no value

  one two three four
0   a   b     c    d
3   a   e     i    o

In [ ]:
df.dropna(axis = 1) # drops the column where there is null value or no value

  one four
0   a    d
1   e    h
2   i    l
3   a    o
4   s    g

In [ ]:
# apply functions

In [ ]:
import pandas as pd
dic = {'A':[1,2,3,4], 'B':[5,6,7,8]}
df = pd.DataFrame(dic)
df

   A  B
0  1  5
1  2  6
2  3  7
3  4  8

In [ ]:
df.apply(sum, axis = 0) # sum across the column

A    10
B    26
dtype: int64

In [ ]:
df.apply(sum, axis = 1) # sum across the row

0     6
1     8
2    10
3    12
dtype: int64

In [ ]:
# filter function

In [ ]:
import pandas as pd
dic = {'A':[1,2,3,4], 'B':[5,6,7,8]}
df = pd.DataFrame(dic)
df

# importing pandas as pd
import pandas as pd

# Creating the Series
sr = pd.Series({'Coca Cola': 45, 'Coke': 40, 'Fanta': 40, 'Dew': 50, 'Thumbs Up':30})

# Print the series
sr

Coca Cola    45
Coke         40
Fanta        40
Dew          50
Thumbs Up    30
dtype: int64

In [ ]:
# filter the series
sr.filter(items = ['Coke', 'Fanta'])

Coke     40
Fanta    40
dtype: int64

In [ ]:
# group by function

In [ ]:
import numpy as np
dic = {
    'Name': ['Bob','Sam','Mary','Alice','Beth'],
    'Status': ['Current','Alumni','Alumni','Alumni','Current'],
    'Fees': ['Due', 'Clear', 'Scholarship', 'Scholarship', 'Due'],
    'Score': [78,68,89,87,76],
    'Score2': [67,87,96,95,np.nan]
}
import pandas as pd
df = pd.DataFrame(dic)
df

    Name   Status         Fees  Score  Score2
0    Bob  Current          Due     78    67.0
1    Sam   Alumni        Clear     68    87.0
2   Mary   Alumni  Scholarship     89    96.0
3  Alice   Alumni  Scholarship     87    95.0
4   Beth  Current          Due     76     NaN

In [ ]:
# grouping categorical data
status = df.groupby("Status")
status.groups

{'Alumni': [1, 2, 3], 'Current': [0, 4]}

In [ ]:
fees = df.groupby("Fees")
# fees.groups
fees.groups.items() # gives in dictionary form

dict_items([('Clear', Index([1], dtype='int64')), ('Due', Index([0, 4], dtype='int64')), ('Scholarship', Index([2, 3], dtype='int64'))])

In [ ]:
for fee_status, students in fees.groups.items():
  # print(fee_status, students)
  if fee_status == "Scholarship":
    for student in students:
      #print(df.iloc[student])
      print(df.iloc[[student]])
      print("-" * 50)
      print("\n")

   Name  Status         Fees  Score  Score2
2  Mary  Alumni  Scholarship     89    96.0
--------------------------------------------------


    Name  Status         Fees  Score  Score2
3  Alice  Alumni  Scholarship     87    95.0
--------------------------------------------------

In [ ]:
df.groupby("Status").max()

        Name         Fees  Score  Score2
Status
Alumni   Sam  Scholarship     89    96.0
Current  Bob          Due     78    67.0

In [ ]:
status.count()

         Name  Fees  Score  Score2
Status
Alumni      3     3      3       3
Current     2     2      2       1

In [ ]:
status.mean(numeric_only=True)

             Score     Score2
Status
Alumni   81.333333  92.666667
Current  77.000000  67.000000

In [ ]:
# aggregation

In [ ]:
import numpy as np
dic = {
    'Name': ['Bob','Sam','Mary','Alice','Beth'],
    'Status': ['Current','Alumni','Alumni','Alumni','Current'],
    'Fees': ['Due', 'Clear', 'Scholarship', 'Scholarship', 'Due'],
    'Score': [78,68,89,87,76],
    'Score2': [67,87,96,95,np.nan],
    'Score3':[100,200,300,400,500]
}
import pandas as pd
df = pd.DataFrame(dic)
df

    Name   Status         Fees  Score  Score2  Score3
0    Bob  Current          Due     78    67.0     100
1    Sam   Alumni        Clear     68    87.0     200
2   Mary   Alumni  Scholarship     89    96.0     300
3  Alice   Alumni  Scholarship     87    95.0     400
4   Beth  Current          Due     76     NaN     500

In [ ]:
status = df.groupby("Status")

In [ ]:
status[df.select_dtypes(include=np.number).columns].agg(['mean','median','std', 'min', 'max'])

             Score                               Score2                   \
              mean median        std min max       mean median       std
Status
Alumni   81.333333   87.0  11.590226  68  89  92.666667   95.0  4.932883
Current  77.000000   77.0   1.414214  76  78  67.000000   67.0       NaN

                    Score3
          min   max   mean median         std  min  max
Status
Alumni   87.0  96.0  300.0  300.0  100.000000  200  400
Current  67.0  67.0  300.0  300.0  282.842712  100  500

In [ ]:
# merge: combine using common columns
import pandas as pd
students = pd.DataFrame({
    "ID": [1, 2, 3],
    "Name": ["Ram", "Hari", "Sita"]
})
marks = pd.DataFrame({
    "ID": [1, 2, 3],
    "Marks": [90, 95, 98]
})
result = pd.merge(students, marks, on="ID")
print(result)

   ID  Name  Marks
0   1   Ram     90
1   2  Hari     95
2   3  Sita     98

In [ ]:
# inner join - default join and keeps only matching IDs
pd.merge(students, marks, on="ID", how="inner")

   ID  Name  Marks
0   1   Ram     90
1   2  Hari     95
2   3  Sita     98

In [ ]:
# left join - keep all rows from left dataframe
pd.merge(students, marks, on="ID", how="left")

   ID  Name  Marks
0   1   Ram     90
1   2  Hari     95
2   3  Sita     98

In [ ]:
# left join - keep all rows from right dataframe
pd.merge(students, marks, on="ID", how="right")

   ID  Name  Marks
0   1   Ram     90
1   2  Hari     95
2   3  Sita     98

In [ ]:
# outer join

In [ ]:
# join
import pandas as pd
students = pd.DataFrame({
    "Name": ["Ram", "Hari", "Sita"]
}, index = [1, 2, 3])
marks = pd.DataFrame({
    "Marks": [90, 95, 98]
}, index = [1, 2, 3])
print(students.join(marks))

   Name  Marks
1   Ram     90
2  Hari     95
3  Sita     98

In [ ]:
# concatenation (using stack)
df1 = pd.DataFrame({
    "Name": ["Ram", "Hari"]
})
df2 = pd.DataFrame({
    "Name": ["Sita", "Gita"]
})
# pd.concat([df1, df2])
pd.concat([df1, df2], ignore_index=True)

   Name
0   Ram
1  Hari
2  Sita
3  Gita

In [ ]:
# concatenation using column wise
df1 = pd.DataFrame({
    "Name": ["Ram", "Hari"]
})
df2 = pd.DataFrame({
    "Name": ["Sita", "Gita"]
})
# pd.concat([df1, df2])
pd.concat([df1, df2], axis = 1)

   Name  Name
0   Ram  Sita
1  Hari  Gita